@LoyaltyAPI_HostAddress = http://localhost:5153

### Calculate Points
POST {{LoyaltyAPI_HostAddress}}/api/v1.0/loyalty/calculate
Content-Type: application/json

{
  "transactionDate": "08-Nov-2025",
  "grandTotal": 45.50,
  "basket": [
    {
      "productId": "PROD001",
      "unitPrice": 10.00,
      "quantity": 2
    },
    {
      "productId": "PROD002",
      "unitPrice": 25.50,
      "quantity": 1
    }
  ]
}

### Calculate Points with Promotion
POST {{LoyaltyAPI_HostAddress}}/api/v1.0/loyalty/calculate
Content-Type: application/json

{
  "transactionDate": "10-Feb-2020",
  "grandTotal": 62.00,
  "basket": [
    {
      "productId": "PRD01",
      "unitPrice": 1.2,
      "quantity": 50
    },
    {
      "productId": "PRD04",
      "unitPrice": 2.3,
      "quantity": 1
    }
  ]
}
