@LoyaltyAPI_HostAddress = http://localhost:5153

### Calculate Points
POST {{LoyaltyAPI_HostAddress}}/api/v1.0/loyalty/calculate
Content-Type: application/json

{
  "transactionDate": "08-Nov-2025",
  "grandTotal": 45.50,
  "basket": [
    {
      "productId": "PROD001",
      "unitPrice": 10.00,
      "quantity": 2
    },
    {
      "productId": "PROD002",
      "unitPrice": 25.50,
      "quantity": 1
    }
  ]
}
